[package]
name = "PasswordGenerator"
version = "0.2.0"
edition = "2021"

[dependencies]
rand = "0.8"  # rand for rng

[[bin]]
name = "PasswordGenerator"
path = "src/main.rs"

# For CLI usage
[features]
cli = []
